# VirtualHere USB Server Docker Image for Linux RISCV64
FROM --platform=$BUILDPLATFORM alpine:3.20 AS downloader

ARG VIRTUALHERE_URL=https://www.virtualhere.com/sites/default/files/usbserver/vhusbdriscv64

RUN apk add --no-cache ca-certificates wget && \
    wget -O /virtualhere "${VIRTUALHERE_URL}" && \
    chmod +x /virtualhere

FROM scratch

WORKDIR /data

EXPOSE 7575
VOLUME ["/data"]

COPY --from=downloader /virtualhere /app/virtualhere

ENTRYPOINT ["/app/virtualhere"]
